import type { Sector } from "./site";

export type Project = {
  slug: string;
  title: string;
  sector: Sector;
  location: string;
  year: string;
  scope: string;
  image: string;
  featured?: boolean;
};

/* NOTE: titres, localisations et années sont déduits des visuels fournis
   et doivent être validés par SAGA avant mise en ligne. */
export const projects: Project[] = [
  {
    slug: "le-chevalier",
    title: "Le Chevalier",
    sector: "Multirésidentiel",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Structure complète — immeuble résidentiel de 4 étages",
    image: "/le-chevalier.webp",
    featured: true,
  },
  {
    slug: "bibliotheque-roberval",
    title: "Bibliothèque municipale",
    sector: "Institutionnel",
    location: "Roberval, QC",
    year: "2023",
    scope: "Charpente et enveloppe — équipement culturel",
    image: "/bibliotheque-roberval.webp",
    featured: true,
  },
  {
    slug: "centre-sante-equilibre",
    title: "Centre de santé l’Équilibre",
    sector: "Institutionnel",
    location: "Saguenay, QC",
    year: "2022",
    scope: "Agrandissement et mise à niveau structurale",
    image: "/centre-sante-equilibre.webp",
    featured: true,
  },
  {
    slug: "microtel",
    title: "Hôtel Microtel",
    sector: "Hôtellerie",
    location: "Saguenay–Lac-Saint-Jean",
    year: "2022",
    scope: "Structure d’un hôtel de quatre étages",
    image: "/microtel.webp",
    featured: true,
  },
  {
    slug: "coderr",
    title: "Coderr",
    sector: "Multirésidentiel",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Ensemble résidentiel multi-bâtiments",
    image: "/coderr.webp",
    featured: true,
  },
  {
    slug: "familiprix",
    title: "Familiprix",
    sector: "Commercial",
    location: "Saguenay, QC",
    year: "2021",
    scope: "Structure d’un bâtiment commercial",
    image: "/familiprix.webp",
  },
  {
    slug: "centre-georges-vezina",
    title: "Centre Georges-Vézina",
    sector: "Institutionnel",
    location: "Chicoutimi, QC",
    year: "2021",
    scope: "Expertise structurale — aréna",
    image: "/centre-georges-vezina.webp",
  },
  {
    slug: "cpe-campus-des-lutins",
    title: "CPE Campus des lutins",
    sector: "Institutionnel",
    location: "Saguenay, QC",
    year: "2022",
    scope: "Structure d’un centre de la petite enfance",
    image: "/cpe-campus-des-lutins.webp",
  },
  {
    slug: "ecole-mont-valin",
    title: "École Mont-Valin",
    sector: "Institutionnel",
    location: "Saint-David-de-Falardeau, QC",
    year: "2022",
    scope: "Réfection et mise aux normes",
    image: "/ecole-mont-valin.webp",
  },
  {
    slug: "ecole-scdm",
    title: "Complexe scolaire",
    sector: "Institutionnel",
    location: "Saguenay, QC",
    year: "2024",
    scope: "Structure d’un complexe scolaire neuf",
    image: "/ecole-scdm.webp",
  },
  {
    slug: "beauvoir",
    title: "Le Beauvoir",
    sector: "Multirésidentiel",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Immeuble résidentiel — structure et fondations",
    image: "/beauvoir.webp",
  },
  {
    slug: "edifice-cim",
    title: "Édifice CIM",
    sector: "Commercial",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Bâtiment de bureaux — structure mixte",
    image: "/edifice-cim.webp",
  },
  {
    slug: "sefar",
    title: "Édifice Sefar",
    sector: "Industriel",
    location: "Saguenay, QC",
    year: "2021",
    scope: "Bâtiment industriel et administratif",
    image: "/sefar.webp",
  },
  {
    slug: "entrepot-tresors",
    title: "Centre de distribution",
    sector: "Industriel",
    location: "Saguenay, QC",
    year: "2022",
    scope: "Charpente d’acier — entrepôt",
    image: "/entrepot-tresors.webp",
  },
  {
    slug: "auberge",
    title: "Auberge riveraine",
    sector: "Hôtellerie",
    location: "Lac-Saint-Jean, QC",
    year: "2021",
    scope: "Structure d’un établissement de villégiature",
    image: "/auberge.webp",
  },
  {
    slug: "chalets",
    title: "Chalets de villégiature",
    sector: "Hôtellerie",
    location: "Saguenay–Lac-Saint-Jean",
    year: "2022",
    scope: "Charpente bois — hébergement touristique",
    image: "/chalets.webp",
  },
  {
    slug: "complexe-aquatique",
    title: "Complexe aquatique",
    sector: "Récréatif",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Structure d’une piscine intérieure",
    image: "/complexe-aquatique.webp",
  },
  {
    slug: "bains-spa",
    title: "Bains nordiques",
    sector: "Récréatif",
    location: "Saguenay–Lac-Saint-Jean",
    year: "2023",
    scope: "Structure d’un spa extérieur",
    image: "/bains-spa.webp",
  },
  {
    slug: "tour-observation",
    title: "Tour d’observation",
    sector: "Récréatif",
    location: "Saguenay–Lac-Saint-Jean",
    year: "2022",
    scope: "Structure de bois — belvédère",
    image: "/tour-observation.webp",
  },
  {
    slug: "pavillon",
    title: "Pavillon d’accueil",
    sector: "Récréatif",
    location: "Saguenay, QC",
    year: "2024",
    scope: "Petit bâtiment d’accueil — structure bois",
    image: "/pavillon.webp",
  },
  {
    slug: "edifice-ardoises",
    title: "Édifice Les Ardoises",
    sector: "Commercial",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Bâtiment mixte commercial et résidentiel",
    image: "/edifice-ardoises.webp",
  },
  {
    slug: "seminaire",
    title: "Ancien séminaire",
    sector: "Patrimonial",
    location: "Chicoutimi, QC",
    year: "2022",
    scope: "Réhabilitation structurale d’un bâtiment patrimonial",
    image: "/seminaire.webp",
  },
  {
    slug: "centre-communautaire",
    title: "Centre communautaire",
    sector: "Institutionnel",
    location: "Saguenay, QC",
    year: "2020",
    scope: "Conception structurale — bâtiment communautaire",
    image: "/centre-communautaire.webp",
  },
  {
    slug: "bibliotheque-interieur",
    title: "Aménagement de bibliothèque",
    sector: "Institutionnel",
    location: "Saguenay, QC",
    year: "2023",
    scope: "Structure intérieure et mezzanine",
    image: "/bibliotheque-interieur.webp",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
